package com.ratingService.entites;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document("ratings")
public class Rating {

    @Id // AutoGenerated by MongoDB
    private String ratingid;
    private String userId;
    private String hotelId;
    private int rating;
    private String feedback;
}
